/* ============================================================
   GALAXY RIDE — TOURISM DESTINATIONS DATA
   Source for the destination tour-taxi page generator.
   distances (dist) are approximate one-way road km from each
   fare origin and are used by the on-page Smart Fare Calculator.
   Edit here, then run:  node scripts/generate-seo.js
   ============================================================ */

// Fare origins used by the Smart Fare Calculator (slug → label)
const FARE_ORIGINS = [
  { slug: 'chennai',     name: 'Chennai' },
  { slug: 'madurai',     name: 'Madurai' },
  { slug: 'bangalore',   name: 'Bengaluru' },
  { slug: 'coimbatore',  name: 'Coimbatore' },
  { slug: 'trichy',      name: 'Trichy' },
  { slug: 'salem',       name: 'Salem' },
  { slug: 'erode',       name: 'Erode' },
  { slug: 'theni',       name: 'Theni' },
  { slug: 'dindigul',    name: 'Dindigul' },
];

// Travel-info table shows distances from these 5 hubs
const INFO_ORIGINS = ['chennai', 'madurai', 'bangalore', 'coimbatore', 'trichy'];

const DESTINATIONS = [
  {
    slug: 'kodaikanal', name: 'Kodaikanal', state: 'Tamil Nadu',
    img: 'public/tourism/Kodaikanal.webp',
    tagline: 'The Princess of Hill Stations — mist-wrapped valleys, a silver star-shaped lake and fragrant pine forests at 2,133m.',
    tags: ['Hill Station', 'Family Trip', 'Honeymoon', 'Weekend Getaway'],
    dist: { chennai: 535, madurai: 115, bangalore: 460, coimbatore: 170, trichy: 200, salem: 260, erode: 215, theni: 90, dindigul: 100 },
    bestSeason: 'April – June & September – October', duration: '2 – 3 days',
    weather: 'Cool 10–20°C year-round; carry light woollens, misty mornings.',
    roads: 'Well-laid ghat road via Batlagundu; 40+ hairpin bends — experienced hill drivers recommended.',
    attractions: [
      { n: 'Kodai Lake', d: 'Star-shaped glacial lake perfect for pedal-boating and cycling.' },
      { n: "Coaker's Walk", d: '1 km cliff-edge promenade with sweeping valley views.' },
      { n: 'Pillar Rocks', d: 'Three dramatic 122m granite pillars wreathed in mist.' },
      { n: 'Green Valley View', d: 'Breathtaking 2,000m sheer-drop valley panorama.' },
      { n: 'Pine Forest', d: 'Photogenic planted pine woods, a film-shoot favourite.' },
      { n: 'Silver Cascade Falls', d: '180-ft roadside waterfall on the way up.' },
    ],
    plans: {
      1: [ { t: 'Morning', d: 'Kodai Lake boating and a stroll around Bryant Park.' },
            { t: 'Afternoon', d: "Coaker's Walk views, then Pillar Rocks and Green Valley View." },
            { t: 'Evening', d: 'Pine Forest photo stop and chocolate shopping at the bazaar.' } ],
      2: [ { t: 'Day 1', d: 'Lake, Bryant Park, Coaker’s Walk and Bear Shola Falls.' },
            { t: 'Day 2', d: 'Pillar Rocks, Pine Forest, Dolphin’s Nose and Silver Cascade on the way down.' } ],
      3: [ { t: 'Day 1', d: 'Arrival, Kodai Lake and Bryant Park sunset.' },
            { t: 'Day 2', d: 'Viewpoints — Coaker’s Walk, Pillar Rocks, Green Valley, Dolphin’s Nose.' },
            { t: 'Day 3', d: 'Kurinji Andavar Temple, Solar Observatory and departure.' } ],
    },
    reviews: [
      { name: 'Suresh K.', city: 'Chennai', text: 'Booked a Kodaikanal package from Chennai. Clean Innova and a driver who knew every viewpoint. Smooth hairpin driving.' },
      { name: 'Anitha R.', city: 'Madurai', text: 'Quick Madurai–Kodaikanal trip, transparent fare, on-time pickup. Will book again.' },
    ],
  },
  {
    slug: 'ooty', name: 'Ooty', state: 'Tamil Nadu',
    img: 'public/tourism/ooty.jpg',
    tagline: 'The Queen of Hill Stations — rolling tea gardens, a UNESCO toy train and crisp Nilgiri air at 2,240m.',
    tags: ['Hill Station', 'Family Trip', 'Honeymoon', 'Weekend Getaway'],
    dist: { chennai: 555, madurai: 280, bangalore: 270, coimbatore: 85, trichy: 330, salem: 200, erode: 150, theni: 300, dindigul: 250 },
    bestSeason: 'October – June', duration: '2 – 3 days',
    weather: 'Pleasant 10–22°C; cold nights in winter, occasional showers.',
    roads: 'Scenic ghat via Mettupalayam or Gudalur; 36 hairpin bends, very well maintained.',
    attractions: [
      { n: 'Nilgiri Mountain Railway', d: 'UNESCO heritage toy train to Coonoor.' },
      { n: 'Ooty Lake', d: 'Boating on a scenic 65-acre artificial lake.' },
      { n: 'Botanical Garden', d: '55 acres of rare flora and a fossil tree.' },
      { n: 'Doddabetta Peak', d: 'Highest point in the Nilgiris at 2,637m.' },
      { n: 'Tea Factory & Museum', d: 'See how Nilgiri tea is grown and processed.' },
      { n: 'Rose Garden', d: 'Terraced garden with thousands of rose varieties.' },
    ],
    plans: {
      1: [ { t: 'Morning', d: 'Doddabetta Peak and a Nilgiri tea factory tour.' },
            { t: 'Afternoon', d: 'Botanical Garden and Ooty Lake boating.' },
            { t: 'Evening', d: 'Rose Garden and Charring Cross shopping.' } ],
      2: [ { t: 'Day 1', d: 'Ooty Lake, Rose Garden, Botanical Garden and Doddabetta.' },
            { t: 'Day 2', d: 'Toy-train ride to Coonoor — Sim’s Park, Lamb’s Rock, Dolphin’s Nose.' } ],
      3: [ { t: 'Day 1', d: 'Arrival, lake and Rose Garden.' },
            { t: 'Day 2', d: 'Tea factory, Doddabetta and Botanical Garden.' },
            { t: 'Day 3', d: 'Coonoor toy train, Avalanche Lake and departure.' } ],
    },
    reviews: [
      { name: 'Vivek M.', city: 'Coimbatore', text: 'Coimbatore to Ooty in under 3 hours, fantastic Sedan and a calm driver on the bends. Fair price.' },
      { name: 'Deepa S.', city: 'Bengaluru', text: 'Family Ooty tour in an Innova. Spacious, punctual and the itinerary suggestions were spot on.' },
    ],
  },
  {
    slug: 'munnar', name: 'Munnar', state: 'Kerala',
    img: 'public/tourism/munnar.jpg',
    tagline: 'An endless sea of emerald tea gardens, misty shola forests and waterfalls in Kerala’s high ranges.',
    tags: ['Hill Station', 'Honeymoon', 'Family Trip', 'Weekend Getaway'],
    dist: { chennai: 590, madurai: 160, bangalore: 470, coimbatore: 150, trichy: 270, salem: 290, erode: 220, theni: 80, dindigul: 180 },
    bestSeason: 'September – May', duration: '2 – 3 days',
    weather: 'Cool 12–22°C; misty and green, heavy rain June–August.',
    roads: 'Smooth ghat via Theni/Bodi or Kochi; scenic tea-estate drive.',
    attractions: [
      { n: 'Eravikulam National Park', d: 'Home of the endangered Nilgiri Tahr.' },
      { n: 'Tea Gardens & Museum', d: 'Tata Tea Museum and rolling estate viewpoints.' },
      { n: 'Mattupetty Dam', d: 'Scenic reservoir framed by shola forest.' },
      { n: 'Attukad Waterfalls', d: 'A cascading 100m waterfall amid greenery.' },
      { n: 'Echo Point', d: 'Lakeside spot famous for its natural echo.' },
      { n: 'Top Station', d: 'Panoramic viewpoint over the Western Ghats.' },
    ],
    plans: {
      1: [ { t: 'Morning', d: 'Eravikulam National Park and a tea-estate viewpoint.' },
            { t: 'Afternoon', d: 'Mattupetty Dam, Echo Point and Kundala Lake.' },
            { t: 'Evening', d: 'Tea Museum and spice-market shopping.' } ],
      2: [ { t: 'Day 1', d: 'Tea Museum, Pothamedu viewpoint and Attukad Falls.' },
            { t: 'Day 2', d: 'Eravikulam Park, Mattupetty, Echo Point and Top Station.' } ],
      3: [ { t: 'Day 1', d: 'Arrival through tea estates and Echo Point sunset.' },
            { t: 'Day 2', d: 'Wildlife, waterfalls and dam circuit.' },
            { t: 'Day 3', d: 'Top Station, spice plantation and departure.' } ],
    },
    reviews: [
      { name: 'Rahul N.', city: 'Madurai', text: 'Madurai–Munnar via Theni was gorgeous. Driver stopped at every viewpoint we wanted. Great value.' },
      { name: 'Priya V.', city: 'Coimbatore', text: 'Honeymoon trip to Munnar, spotless Sedan and courteous chauffeur. Highly recommend Galaxy Ride.' },
    ],
  },
  {
    slug: 'alleppey', name: 'Alleppey', state: 'Kerala',
    img: 'public/tourism/alleppey.jpg',
    tagline: 'The Venice of the East — glide through palm-fringed backwater canals on a traditional houseboat.',
    tags: ['Backwaters', 'Honeymoon', 'Family Trip', 'Weekend Getaway'],
    dist: { chennai: 750, madurai: 320, bangalore: 560, coimbatore: 320, trichy: 420, salem: 430, erode: 370, theni: 290, dindigul: 350 },
    bestSeason: 'November – February', duration: '1 – 2 days',
    weather: 'Warm humid 24–32°C; pleasant in winter, monsoon June–Sept.',
    roads: 'Flat highway via Kochi or Kottayam; easy, well-paved roads.',
    attractions: [
      { n: 'Houseboat Cruise', d: 'Overnight stay on a traditional kettuvallam.' },
      { n: 'Vembanad Lake', d: 'The largest lake in Kerala, ideal for sunsets.' },
      { n: 'Alleppey Beach', d: 'Calm, palm-lined coastline with an old pier.' },
      { n: 'Kuttanad', d: 'The rice bowl of Kerala, below sea level.' },
      { n: 'Marari Beach', d: 'Quiet, clean fishing-village beach nearby.' },
      { n: 'Pathiramanal Island', d: 'Sanctuary for migratory birds on the lake.' },
    ],
    plans: {
      1: [ { t: 'Morning', d: 'Board the houseboat and cruise the main canals.' },
            { t: 'Afternoon', d: 'Lunch aboard, paddy-field villages and toddy stops.' },
            { t: 'Evening', d: 'Sunset on Vembanad Lake, then Alleppey Beach.' } ],
      2: [ { t: 'Day 1', d: 'Houseboat check-in, backwater cruise and overnight stay.' },
            { t: 'Day 2', d: 'Morning village walk, Marari Beach and departure.' } ],
      3: [ { t: 'Day 1', d: 'Arrival and houseboat cruise.' },
            { t: 'Day 2', d: 'Kuttanad, Pathiramanal Island and beach.' },
            { t: 'Day 3', d: 'Nearby Kumarakom bird sanctuary and departure.' } ],
    },
    reviews: [
      { name: 'Karthik R.', city: 'Chennai', text: 'Long drive from Chennai but the Innova was super comfortable and the driver handled it solo. Backwaters were unreal.' },
      { name: 'Sneha P.', city: 'Trichy', text: 'Trichy to Alleppey was smooth and the fare was clear upfront. No surprises.' },
    ],
  },
  {
    slug: 'thekkady', name: 'Thekkady', state: 'Kerala',
    img: null,
    tagline: 'Spice-scented jungles and the Periyar Tiger Reserve — Kerala’s premier wildlife and plantation getaway.',
    tags: ['Wildlife', 'Family Trip', 'Weekend Getaway', 'Nature'],
    dist: { chennai: 600, madurai: 140, bangalore: 480, coimbatore: 200, trichy: 270, salem: 320, erode: 250, theni: 70, dindigul: 180 },
    bestSeason: 'October – March', duration: '1 – 2 days',
    weather: 'Pleasant 15–28°C; cool evenings, lush after the monsoon.',
    roads: 'Good ghat road via Theni–Kumily; winding final stretch.',
    attractions: [
      { n: 'Periyar Lake Cruise', d: 'Boat safari to spot elephants, bison and deer.' },
      { n: 'Periyar Tiger Reserve', d: 'Guided nature walks and bamboo rafting.' },
      { n: 'Spice Plantations', d: 'Cardamom, pepper and vanilla estate tours.' },
      { n: 'Kumily Town', d: 'Bustling spice market and homestays.' },
      { n: 'Mangala Devi Temple', d: 'Ancient hilltop temple amid forest (seasonal).' },
      { n: 'Kathakali & Kalari Shows', d: 'Traditional Kerala dance and martial arts.' },
    ],
    plans: {
      1: [ { t: 'Morning', d: 'Periyar Lake boat cruise and wildlife spotting.' },
            { t: 'Afternoon', d: 'Guided spice plantation tour with tasting.' },
            { t: 'Evening', d: 'Kathakali and Kalaripayattu cultural show.' } ],
      2: [ { t: 'Day 1', d: 'Lake cruise, spice gardens and Kumily market.' },
            { t: 'Day 2', d: 'Nature walk or bamboo rafting, then departure.' } ],
      3: [ { t: 'Day 1', d: 'Arrival and evening cultural shows.' },
            { t: 'Day 2', d: 'Periyar safari and plantation tour.' },
            { t: 'Day 3', d: 'Mangala Devi Temple and departure.' } ],
    },
    reviews: [
      { name: 'Manoj T.', city: 'Madurai', text: 'Theni and Madurai friends did a Thekkady weekend — driver was punctual and the SUV handled the ghats easily.' },
      { name: 'Lakshmi G.', city: 'Coimbatore', text: 'Loved the Periyar cruise. Galaxy Ride fare was honest and the cab was clean.' },
    ],
  },
  {
    slug: 'vagamon', name: 'Vagamon', state: 'Kerala',
    img: null,
    tagline: 'Rolling emerald meadows, pine valleys and paragliding skies — Kerala’s offbeat ‘Scotland of Asia’.',
    tags: ['Hill Station', 'Adventure', 'Honeymoon', 'Weekend Getaway'],
    dist: { chennai: 650, madurai: 200, bangalore: 520, coimbatore: 230, trichy: 320, salem: 360, erode: 290, theni: 130, dindigul: 230 },
    bestSeason: 'August – February', duration: '1 – 2 days',
    weather: 'Cool 10–23°C; foggy meadows, breezy and green.',
    roads: 'Scenic but narrow ghat via Theni/Kuttikkanam; careful driving needed.',
    attractions: [
      { n: 'Vagamon Meadows', d: 'Endless rolling green hills, a trekking favourite.' },
      { n: 'Pine Forest', d: 'Planted pine valley with a swing and walking trails.' },
      { n: 'Paragliding Point', d: 'One of South India’s top paragliding spots.' },
      { n: 'Suicide / Marmala Point', d: 'Dramatic cliff viewpoints and a waterfall.' },
      { n: 'Thangal Para', d: 'Sacred rock with valley views.' },
      { n: 'Tea Estates', d: 'Quiet plantation drives and viewpoints.' },
    ],
    plans: {
      1: [ { t: 'Morning', d: 'Vagamon meadows trek and Pine Forest.' },
            { t: 'Afternoon', d: 'Paragliding point and Marmala viewpoint.' },
            { t: 'Evening', d: 'Tea estate sunset drive.' } ],
      2: [ { t: 'Day 1', d: 'Meadows, Pine Forest and Suicide Point.' },
            { t: 'Day 2', d: 'Thangal Para, Mundakayam waterfalls and departure.' } ],
      3: [ { t: 'Day 1', d: 'Arrival and meadow sunset.' },
            { t: 'Day 2', d: 'Adventure day — paragliding and trekking.' },
            { t: 'Day 3', d: 'Nearby Kuttikkanam and departure.' } ],
    },
    reviews: [
      { name: 'Arjun D.', city: 'Madurai', text: 'Offbeat Vagamon trip from Madurai. The driver knew the narrow roads well and we felt safe throughout.' },
      { name: 'Reka S.', city: 'Theni', text: 'Short hop from Theni, lovely meadows. Booking and fare were straightforward.' },
    ],
  },
  {
    slug: 'wayanad', name: 'Wayanad', state: 'Kerala',
    img: null,
    tagline: 'Lush forests, waterfalls, caves and wildlife in Kerala’s greenest highland district.',
    tags: ['Wildlife', 'Family Trip', 'Adventure', 'Weekend Getaway'],
    dist: { chennai: 640, madurai: 420, bangalore: 280, coimbatore: 180, trichy: 460, salem: 290, erode: 230, theni: 440, dindigul: 390 },
    bestSeason: 'October – May', duration: '2 – 3 days',
    weather: 'Pleasant 15–28°C; misty hills, very green post-monsoon.',
    roads: 'Good roads via Gudalur or Bandipur; forest stretches with wildlife crossings.',
    attractions: [
      { n: 'Edakkal Caves', d: 'Prehistoric petroglyphs after a short trek.' },
      { n: 'Banasura Sagar Dam', d: 'India’s largest earthen dam with island views.' },
      { n: 'Soochipara Falls', d: 'A three-tier waterfall popular for rappelling.' },
      { n: 'Chembra Peak', d: 'Heart-shaped lake trek to Wayanad’s highest point.' },
      { n: 'Muthanga Sanctuary', d: 'Jeep safari for elephants and deer.' },
      { n: 'Pookode Lake', d: 'Freshwater lake with pedal boating.' },
    ],
    plans: {
      1: [ { t: 'Morning', d: 'Edakkal Caves trek and petroglyphs.' },
            { t: 'Afternoon', d: 'Soochipara Falls and Pookode Lake.' },
            { t: 'Evening', d: 'Banasura Sagar Dam sunset.' } ],
      2: [ { t: 'Day 1', d: 'Edakkal Caves, Soochipara Falls and Pookode Lake.' },
            { t: 'Day 2', d: 'Muthanga safari, Banasura Dam and departure.' } ],
      3: [ { t: 'Day 1', d: 'Arrival and Pookode Lake.' },
            { t: 'Day 2', d: 'Chembra Peak trek and waterfalls.' },
            { t: 'Day 3', d: 'Wildlife safari and departure.' } ],
    },
    reviews: [
      { name: 'Gopal R.', city: 'Coimbatore', text: 'Coimbatore to Wayanad through Bandipur — beautiful drive and a careful driver in the forest zone.' },
      { name: 'Divya M.', city: 'Bengaluru', text: 'Family Wayanad tour in an Innova. Roomy, clean and the fare estimate matched the final bill.' },
    ],
  },
  {
    slug: 'coorg', name: 'Coorg', state: 'Karnataka',
    img: 'public/tourism/coorg3.jpg',
    tagline: 'The Scotland of India — coffee and spice estates, misty valleys and a proud warrior culture.',
    tags: ['Hill Station', 'Honeymoon', 'Family Trip', 'Nature'],
    dist: { chennai: 560, madurai: 460, bangalore: 265, coimbatore: 290, trichy: 470, salem: 330, erode: 300, theni: 480, dindigul: 430 },
    bestSeason: 'October – May', duration: '2 – 3 days',
    weather: 'Cool 15–28°C; misty mornings, heavy rain June–Sept.',
    roads: 'Good highways via Mysore; gentle estate roads around Madikeri.',
    attractions: [
      { n: 'Abbey Falls', d: 'A 70-ft waterfall set inside a coffee estate.' },
      { n: 'Dubare Elephant Camp', d: 'Bathe and feed elephants by the river.' },
      { n: 'Namdroling Monastery', d: 'The Golden Temple of Tibetan Buddhism.' },
      { n: "Raja's Seat", d: 'Sunset garden viewpoint over the valleys.' },
      { n: 'Coffee Plantations', d: 'Estate walks and homestays with fresh brews.' },
      { n: 'Talacauvery', d: 'Sacred birthplace of the river Cauvery.' },
    ],
    plans: {
      1: [ { t: 'Morning', d: 'Abbey Falls and a coffee plantation walk.' },
            { t: 'Afternoon', d: 'Dubare Elephant Camp and Nisargadhama.' },
            { t: 'Evening', d: "Raja's Seat sunset and Madikeri market." } ],
      2: [ { t: 'Day 1', d: 'Abbey Falls, plantation tour and Raja’s Seat.' },
            { t: 'Day 2', d: 'Dubare camp, Golden Temple and Bylakuppe.' } ],
      3: [ { t: 'Day 1', d: 'Arrival and Madikeri sights.' },
            { t: 'Day 2', d: 'Wildlife, monastery and waterfalls.' },
            { t: 'Day 3', d: 'Talacauvery, Brahmagiri viewpoint and departure.' } ],
    },
    reviews: [
      { name: 'Naveen B.', city: 'Bengaluru', text: 'Bengaluru–Coorg weekend, crisp Sedan and a smooth booking. Driver suggested a great plantation stay.' },
      { name: 'Meera K.', city: 'Chennai', text: 'Long trip from Chennai handled brilliantly. Transparent fare with tolls shown separately.' },
    ],
  },
  {
    slug: 'mysore', name: 'Mysore', state: 'Karnataka',
    img: null,
    tagline: 'The City of Palaces — royal Wodeyar heritage, illuminated palaces, silk and sandalwood.',
    tags: ['Heritage', 'Family Trip', 'Temple Tour', 'Weekend Getaway'],
    dist: { chennai: 470, madurai: 430, bangalore: 145, coimbatore: 200, trichy: 380, salem: 250, erode: 220, theni: 450, dindigul: 400 },
    bestSeason: 'October – March', duration: '1 – 2 days',
    weather: 'Pleasant 18–30°C; great around Dasara festival in autumn.',
    roads: 'Excellent 6-lane expressway from Bengaluru; smooth all around.',
    attractions: [
      { n: 'Mysore Palace', d: 'Indo-Saracenic royal palace, dazzling when lit.' },
      { n: 'Chamundi Hills', d: 'Hilltop temple and the giant Nandi statue.' },
      { n: 'Brindavan Gardens', d: 'Musical fountain and terraced gardens at KRS dam.' },
      { n: 'St. Philomena’s Church', d: 'One of India’s tallest neo-Gothic churches.' },
      { n: 'Mysore Zoo', d: 'One of the oldest, best-kept zoos in India.' },
      { n: 'Devaraja Market', d: 'Vibrant bazaar for flowers, incense and silk.' },
    ],
    plans: {
      1: [ { t: 'Morning', d: 'Mysore Palace and Jaganmohan art gallery.' },
            { t: 'Afternoon', d: 'Chamundi Hills temple and Mysore Zoo.' },
            { t: 'Evening', d: 'Brindavan Gardens musical fountain.' } ],
      2: [ { t: 'Day 1', d: 'Palace, Chamundi Hills and Devaraja Market.' },
            { t: 'Day 2', d: 'Brindavan Gardens, St. Philomena’s and Srirangapatna.' } ],
      3: [ { t: 'Day 1', d: 'Arrival and palace illumination.' },
            { t: 'Day 2', d: 'Temples, zoo and gardens.' },
            { t: 'Day 3', d: 'Srirangapatna and Ranganathittu birds, then departure.' } ],
    },
    reviews: [
      { name: 'Ravi S.', city: 'Bengaluru', text: 'Bengaluru to Mysore on the expressway in 2.5 hours. Comfortable Sedan and a polite driver.' },
      { name: 'Janani P.', city: 'Salem', text: 'Family Mysore-Coorg combo trip. Galaxy Ride gave a clear package fare and a spotless Innova.' },
    ],
  },
  {
    slug: 'tirupati', name: 'Tirupati', state: 'Andhra Pradesh',
    img: 'public/tourism/tirupati.jpg',
    tagline: 'The world’s most-visited temple — seek the blessings of Lord Venkateswara atop the sacred Tirumala Hills.',
    tags: ['Temple Tour', 'Pilgrimage', 'Family Trip', 'Weekend Getaway'],
    dist: { chennai: 135, madurai: 590, bangalore: 250, coimbatore: 620, trichy: 460, salem: 360, erode: 430, theni: 620, dindigul: 540 },
    bestSeason: 'September – February', duration: '1 – 2 days',
    weather: 'Warm 20–35°C; cooler on the hills, plan early darshan.',
    roads: 'Excellent highway from Chennai; ghat road up to Tirumala.',
    attractions: [
      { n: 'Tirumala Venkateswara Temple', d: 'The richest, most-visited shrine in the world.' },
      { n: 'Akasha Ganga', d: 'Sacred waterfall on the temple hill.' },
      { n: 'Sri Padmavathi Temple', d: 'Goddess Padmavathi shrine at Tiruchanur.' },
      { n: 'Silathoranam', d: 'Natural rock arch on the Tirumala Hills.' },
      { n: 'TTD Gardens & Museum', d: 'Temple art, history and gardens.' },
      { n: 'Chandragiri Fort', d: '11th-century fort and palace nearby.' },
    ],
    plans: {
      1: [ { t: 'Morning', d: 'Tirumala darshan with pre-booked time slot.' },
            { t: 'Afternoon', d: 'Collect laddu prasadam; Akasha Ganga and Silathoranam.' },
            { t: 'Evening', d: 'Sri Padmavathi Temple at Tiruchanur.' } ],
      2: [ { t: 'Day 1', d: 'Tirumala darshan and hill temples.' },
            { t: 'Day 2', d: 'Padmavathi Temple, Chandragiri Fort and departure.' } ],
      3: [ { t: 'Day 1', d: 'Arrival and local temples.' },
            { t: 'Day 2', d: 'Tirumala darshan and prasadam.' },
            { t: 'Day 3', d: 'Kanipakam or Srikalahasti and departure.' } ],
    },
    reviews: [
      { name: 'Sai Krishna', city: 'Chennai', text: 'Chennai to Tirupati and back in a day. Driver arrived at 4 AM as promised — perfect for early darshan.' },
      { name: 'Bhuvana R.', city: 'Bengaluru', text: 'Smooth pilgrimage trip, fair fixed fare. The cab was clean and the driver very respectful.' },
    ],
  },
  {
    slug: 'madurai', name: 'Madurai', state: 'Tamil Nadu',
    img: 'public/tourism/Madurai_d5167323e4.webp',
    tagline: 'The Temple City — 2,500 years of Dravidian heritage crowned by the soaring Meenakshi Amman Temple.',
    tags: ['Temple Tour', 'Heritage', 'Family Trip', 'Weekend Getaway'],
    dist: { chennai: 460, madurai: null, bangalore: 430, coimbatore: 215, trichy: 140, salem: 230, erode: 185, theni: 75, dindigul: 65 },
    bestSeason: 'October – March', duration: '1 – 2 days',
    weather: 'Hot 25–38°C; visit temples early morning and evening.',
    roads: 'Excellent NH from all directions; a major South TN hub.',
    attractions: [
      { n: 'Meenakshi Amman Temple', d: '14 towering gopurams and a sea of sculpture.' },
      { n: 'Thirumalai Nayakkar Mahal', d: 'Grand 17th-century Indo-Saracenic palace.' },
      { n: 'Gandhi Memorial Museum', d: 'Powerful exhibits in a historic palace.' },
      { n: 'Teppakulam', d: 'Vast temple tank with a central mandapam.' },
      { n: 'Azhagar Kovil', d: 'Hill temple of Lord Vishnu, 21 km out.' },
      { n: 'Madurai Bazaar', d: 'Jasmine, silk and the famous Jigarthanda.' },
    ],
    plans: {
      1: [ { t: 'Morning', d: 'Meenakshi Temple darshan and all four galleries.' },
            { t: 'Afternoon', d: 'Thirumalai Nayakkar Palace and Gandhi Museum.' },
            { t: 'Evening', d: 'Teppakulam and Jigarthanda at Town Hall.' } ],
      2: [ { t: 'Day 1', d: 'Meenakshi Temple, palace and museum.' },
            { t: 'Day 2', d: 'Azhagar Kovil, Pazhamudircholai and shopping.' } ],
      3: [ { t: 'Day 1', d: 'Arrival and Meenakshi evening aarti.' },
            { t: 'Day 2', d: 'Heritage circuit across the city.' },
            { t: 'Day 3', d: 'Day trip to Kodaikanal or Rameswaram.' } ],
    },
    reviews: [
      { name: 'Prakash V.', city: 'Chennai', text: 'Chennai–Madurai overnight temple trip. Driver was experienced and the Sedan very comfy for the long haul.' },
      { name: 'Geetha L.', city: 'Trichy', text: 'Short Trichy to Madurai hop, on time and affordable. Booking was effortless.' },
    ],
  },
  {
    slug: 'rameswaram', name: 'Rameswaram', state: 'Tamil Nadu',
    img: 'public/tourism/rameshwaram.webp',
    tagline: 'A sacred island where the legendary Ram Setu begins — temples, the Pamban bridge and ghostly Dhanushkodi.',
    tags: ['Temple Tour', 'Pilgrimage', 'Family Trip', 'Beach'],
    dist: { chennai: 560, madurai: 175, bangalore: 600, coimbatore: 380, trichy: 320, salem: 410, erode: 360, theni: 250, dindigul: 240 },
    bestSeason: 'October – April', duration: '1 – 2 days',
    weather: 'Warm coastal 24–34°C; breezy, can be windy near Dhanushkodi.',
    roads: 'Good highway via Madurai; the iconic Pamban sea bridge to the island.',
    attractions: [
      { n: 'Ramanathaswamy Temple', d: 'India’s longest temple corridor (1,212m).' },
      { n: 'Agnitheertham', d: 'Sacred sea-shore bathing ghat.' },
      { n: 'Pamban Bridge', d: 'Iconic rail-and-road sea bridge.' },
      { n: 'Dhanushkodi', d: 'Ghost town at the tip where two seas meet.' },
      { n: 'Dr. APJ Abdul Kalam Memorial', d: 'Tribute to the Missile Man at his birthplace.' },
      { n: 'Kothandaramaswamy Temple', d: 'Lone temple that survived the 1964 cyclone.' },
    ],
    plans: {
      1: [ { t: 'Morning', d: 'Agnitheertham bath and Ramanathaswamy darshan.' },
            { t: 'Afternoon', d: 'Dhanushkodi drive and the Tip of India.' },
            { t: 'Evening', d: 'Pamban Bridge sunset and Kalam Memorial.' } ],
      2: [ { t: 'Day 1', d: 'Temple, 22 theerthams and Agnitheertham.' },
            { t: 'Day 2', d: 'Dhanushkodi, Kothandaramaswamy and departure.' } ],
      3: [ { t: 'Day 1', d: 'Arrival and temple darshan.' },
            { t: 'Day 2', d: 'Dhanushkodi, memorial and beaches.' },
            { t: 'Day 3', d: 'Day trip towards Madurai and departure.' } ],
    },
    reviews: [
      { name: 'Senthil M.', city: 'Madurai', text: 'Madurai to Rameswaram across the Pamban bridge — unforgettable. Driver took us safely to Dhanushkodi too.' },
      { name: 'Usha R.', city: 'Chennai', text: 'Pilgrimage trip from Chennai. Clean cab, fair fare and a knowledgeable driver.' },
    ],
  },
  {
    slug: 'kanyakumari', name: 'Kanyakumari', state: 'Tamil Nadu',
    img: null,
    tagline: 'Land’s End of India — where three seas meet and you can watch the sun rise and set over the same horizon.',
    tags: ['Beach', 'Temple Tour', 'Family Trip', 'Weekend Getaway'],
    dist: { chennai: 700, madurai: 240, bangalore: 680, coimbatore: 350, trichy: 380, salem: 450, erode: 400, theni: 250, dindigul: 310 },
    bestSeason: 'October – March', duration: '1 – 2 days',
    weather: 'Warm coastal 24–34°C; sea breeze, brilliant sunrises.',
    roads: 'Good highway via Tirunelveli/Nagercoil; flat coastal roads.',
    attractions: [
      { n: 'Vivekananda Rock Memorial', d: 'Island shrine reached by ferry.' },
      { n: 'Thiruvalluvar Statue', d: '133-ft monument to the Tamil poet-saint.' },
      { n: 'Sunrise & Sunset Point', d: 'See both over the confluence of three seas.' },
      { n: 'Kumari Amman Temple', d: 'Ancient seashore temple to the Goddess.' },
      { n: 'Gandhi Mandapam', d: 'Memorial built where Gandhi’s ashes were kept.' },
      { n: 'Thanumalayan Temple', d: 'Historic temple at nearby Suchindram.' },
    ],
    plans: {
      1: [ { t: 'Morning', d: 'Sunrise at the beach and Kumari Amman Temple.' },
            { t: 'Afternoon', d: 'Ferry to Vivekananda Rock and Thiruvalluvar Statue.' },
            { t: 'Evening', d: 'Sunset point and Gandhi Mandapam.' } ],
      2: [ { t: 'Day 1', d: 'Sunrise, rock memorial and temples.' },
            { t: 'Day 2', d: 'Suchindram, Padmanabhapuram Palace and departure.' } ],
      3: [ { t: 'Day 1', d: 'Arrival and sunset point.' },
            { t: 'Day 2', d: 'Sunrise, memorials and temples.' },
            { t: 'Day 3', d: 'Nagercoil and Thirparappu Falls, then departure.' } ],
    },
    reviews: [
      { name: 'Antony J.', city: 'Madurai', text: 'Madurai to Kanyakumari sunrise trip. Driver started at midnight so we caught the sunrise — superb service.' },
      { name: 'Kavya N.', city: 'Coimbatore', text: 'Comfortable Innova for the family, clear fare and a smooth coastal drive.' },
    ],
  },
  {
    slug: 'yercaud', name: 'Yercaud', state: 'Tamil Nadu',
    img: null,
    tagline: 'A serene coffee-scented hill retreat in the Shevaroy Hills — the quiet alternative to Ooty.',
    tags: ['Hill Station', 'Weekend Getaway', 'Family Trip', 'Nature'],
    dist: { chennai: 360, madurai: 250, bangalore: 200, coimbatore: 190, trichy: 160, salem: 35, erode: 100, theni: 280, dindigul: 190 },
    bestSeason: 'October – June', duration: '1 – 2 days',
    weather: 'Pleasant 13–27°C; cool, green and uncrowded.',
    roads: 'Short, well-paved ghat from Salem; 20 hairpin bends.',
    attractions: [
      { n: 'Yercaud Lake', d: 'Emerald lake with boating and a garden.' },
      { n: "Pagoda Point", d: 'Cairn viewpoint over the plains.' },
      { n: "Lady's Seat", d: 'Sunset viewpoint overlooking Salem city.' },
      { n: 'Kiliyur Falls', d: 'A 300-ft waterfall after a short trek.' },
      { n: 'Coffee & Spice Estates', d: 'Plantation walks and fresh brews.' },
      { n: 'Bear’s Cave', d: 'Rock caves linked to the Shevaroy temple.' },
    ],
    plans: {
      1: [ { t: 'Morning', d: 'Yercaud Lake boating and the rose garden.' },
            { t: 'Afternoon', d: "Pagoda Point and Lady's Seat viewpoints." },
            { t: 'Evening', d: 'Coffee estate walk and sunset.' } ],
      2: [ { t: 'Day 1', d: 'Lake, viewpoints and Kiliyur Falls.' },
            { t: 'Day 2', d: 'Shevaroy temple, Bear’s Cave and departure.' } ],
      3: [ { t: 'Day 1', d: 'Arrival and lake.' },
            { t: 'Day 2', d: 'Viewpoints, falls and estates.' },
            { t: 'Day 3', d: 'Botanical garden and departure.' } ],
    },
    reviews: [
      { name: 'Mohan R.', city: 'Salem', text: 'Quick Salem to Yercaud escape — driver handled the 20 bends smoothly. Great value for a day trip.' },
      { name: 'Sridevi K.', city: 'Erode', text: 'Peaceful weekend, clean Sedan and honest pricing from Galaxy Ride.' },
    ],
  },
  {
    slug: 'valparai', name: 'Valparai', state: 'Tamil Nadu',
    img: null,
    tagline: 'Tea-carpeted hills, 40 hairpin bends and abundant wildlife in the Anamalai ranges.',
    tags: ['Hill Station', 'Wildlife', 'Nature', 'Weekend Getaway'],
    dist: { chennai: 570, madurai: 230, bangalore: 410, coimbatore: 100, trichy: 290, salem: 230, erode: 165, theni: 200, dindigul: 215 },
    bestSeason: 'September – March', duration: '1 – 2 days',
    weather: 'Cool 15–25°C; misty, frequent wildlife sightings.',
    roads: 'Dramatic ghat via Pollachi with 40 hairpin bends — skilled hill drivers a must.',
    attractions: [
      { n: 'Aliyar Dam', d: 'Scenic reservoir at the foot of the ghats.' },
      { n: 'Monkey Falls', d: 'A roadside waterfall on the climb up.' },
      { n: 'Nirar Dam & Tea Estates', d: 'Endless tea gardens and viewpoints.' },
      { n: 'Sholayar Dam', d: 'One of Asia’s deepest dams amid forest.' },
      { n: 'Loam’s View Point', d: 'Panoramic plains and ghat view.' },
      { n: 'Anamalai Tiger Reserve', d: 'Wildlife including elephants and lion-tailed macaques.' },
    ],
    plans: {
      1: [ { t: 'Morning', d: 'Aliyar Dam and Monkey Falls on the climb.' },
            { t: 'Afternoon', d: 'Tea estates, Nirar Dam and Loam’s View Point.' },
            { t: 'Evening', d: 'Sholayar Dam and wildlife spotting.' } ],
      2: [ { t: 'Day 1', d: 'Ghat climb, dams and tea estate drives.' },
            { t: 'Day 2', d: 'Anamalai safari and viewpoints, then departure.' } ],
      3: [ { t: 'Day 1', d: 'Arrival and tea estates.' },
            { t: 'Day 2', d: 'Dams, falls and wildlife.' },
            { t: 'Day 3', d: 'Valparai town and departure.' } ],
    },
    reviews: [
      { name: 'Bala S.', city: 'Coimbatore', text: 'Coimbatore to Valparai — the 40 bends were no problem for our driver. Saw elephants on the way!' },
      { name: 'Hema D.', city: 'Erode', text: 'Beautiful tea country trip. The SUV was perfect and the fare was clearly explained.' },
    ],
  },
  {
    slug: 'courtallam', name: 'Courtallam', state: 'Tamil Nadu',
    img: null,
    tagline: 'The Spa of South India — a cluster of medicinal waterfalls below the Western Ghats.',
    tags: ['Waterfalls', 'Family Trip', 'Nature', 'Weekend Getaway'],
    dist: { chennai: 620, madurai: 160, bangalore: 590, coimbatore: 320, trichy: 300, salem: 380, erode: 330, theni: 180, dindigul: 230 },
    bestSeason: 'June – September (monsoon falls)', duration: '1 – 2 days',
    weather: 'Warm 24–34°C; falls are fullest during the southwest monsoon.',
    roads: 'Good roads via Tenkasi; easy access to the falls.',
    attractions: [
      { n: 'Main Falls (Peraruvi)', d: 'The famous central cascade with bathing areas.' },
      { n: 'Five Falls (Aintharuvi)', d: 'Water splits into five scenic streams.' },
      { n: 'Old Courtallam Falls', d: 'Quieter falls amid greenery.' },
      { n: 'Tiger Falls', d: 'A gentle, family-friendly cascade.' },
      { n: 'Honey Falls', d: 'A short trek to a secluded waterfall.' },
      { n: 'Thirukutralanathar Temple', d: 'Ancient Shiva temple in the town.' },
    ],
    plans: {
      1: [ { t: 'Morning', d: 'Main Falls bath and the Thirukutralanathar Temple.' },
            { t: 'Afternoon', d: 'Five Falls and Old Courtallam Falls.' },
            { t: 'Evening', d: 'Tiger Falls and local market.' } ],
      2: [ { t: 'Day 1', d: 'Main Falls, Five Falls and temple.' },
            { t: 'Day 2', d: 'Honey Falls trek, Shenbagadevi and departure.' } ],
      3: [ { t: 'Day 1', d: 'Arrival and Main Falls.' },
            { t: 'Day 2', d: 'Falls circuit across the town.' },
            { t: 'Day 3', d: 'Tenkasi temple and departure.' } ],
    },
    reviews: [
      { name: 'Ramesh P.', city: 'Madurai', text: 'Monsoon Courtallam trip from Madurai. Driver knew which falls were flowing best. Lovely day out.' },
      { name: 'Vidya S.', city: 'Theni', text: 'Family waterfalls trip, smooth booking and a clean cab. Recommended.' },
    ],
  },
  {
    slug: 'meghamalai', name: 'Meghamalai', state: 'Tamil Nadu',
    img: null,
    tagline: 'The ‘High Wavy Mountains’ — offbeat cardamom and tea hills wrapped in cloud near Theni.',
    tags: ['Hill Station', 'Offbeat', 'Nature', 'Weekend Getaway'],
    dist: { chennai: 560, madurai: 100, bangalore: 490, coimbatore: 230, trichy: 230, salem: 320, erode: 260, theni: 50, dindigul: 150 },
    bestSeason: 'September – March', duration: '1 – 2 days',
    weather: 'Cool 12–24°C; misty, remote and very green.',
    roads: 'Narrow, steep estate ghat from Theni — strong 4×4/SUV and hill drivers advised.',
    attractions: [
      { n: 'Tea & Cardamom Estates', d: 'Cloud-draped plantations and viewpoints.' },
      { n: 'Highwavys Viewpoint', d: 'Sweeping views over the plains and dams.' },
      { n: 'Vellimalai', d: 'Scenic peak and trekking trails.' },
      { n: 'Suruli Falls', d: 'A two-tier waterfall near the base.' },
      { n: 'Manalar Dam', d: 'Quiet reservoir amid forest.' },
      { n: 'Cloud Land', d: 'Mist-wrapped meadows and estate bungalows.' },
    ],
    plans: {
      1: [ { t: 'Morning', d: 'Estate drive and Highwavys viewpoint.' },
            { t: 'Afternoon', d: 'Manalar Dam and Cloud Land meadows.' },
            { t: 'Evening', d: 'Suruli Falls on the way down.' } ],
      2: [ { t: 'Day 1', d: 'Tea estates, viewpoints and dam.' },
            { t: 'Day 2', d: 'Vellimalai trek, Suruli Falls and departure.' } ],
      3: [ { t: 'Day 1', d: 'Arrival and estate sunset.' },
            { t: 'Day 2', d: 'Viewpoints, dams and trails.' },
            { t: 'Day 3', d: 'Suruli Falls and departure.' } ],
    },
    reviews: [
      { name: 'Selvam K.', city: 'Theni', text: 'Theni to Meghamalai is steep and remote — our driver was excellent on the estate roads. Truly offbeat.' },
      { name: 'Nithya R.', city: 'Madurai', text: 'Loved the misty estates. Galaxy Ride arranged an SUV which was the right call.' },
    ],
  },
  {
    slug: 'yelagiri', name: 'Yelagiri', state: 'Tamil Nadu',
    img: null,
    tagline: 'A compact hill town of orchards, a lake and adventure sports — an easy weekend escape near Bengaluru and Chennai.',
    tags: ['Hill Station', 'Adventure', 'Family Trip', 'Weekend Getaway'],
    dist: { chennai: 230, madurai: 350, bangalore: 160, coimbatore: 360, trichy: 280, salem: 130, erode: 180, theni: 380, dindigul: 300 },
    bestSeason: 'November – June', duration: '1 – 2 days',
    weather: 'Pleasant 14–28°C; mild and breezy on the hills.',
    roads: 'Smooth ghat with 14 hairpin bends from Ponneri; well maintained.',
    attractions: [
      { n: 'Punganur Lake', d: 'Man-made lake with boating and a park.' },
      { n: 'Swamimalai Hills', d: 'Trekking peak with valley views.' },
      { n: 'Jalagamparai Falls', d: 'Seasonal waterfall on the Attaru river.' },
      { n: 'Nilavoor Lake', d: 'Quiet lake for boating and picnics.' },
      { n: 'Paragliding & Zip-line', d: 'Adventure activities at Telescope House.' },
      { n: 'Velavan Temple', d: 'Hilltop Murugan temple with views.' },
    ],
    plans: {
      1: [ { t: 'Morning', d: 'Punganur Lake boating and the herbal farm.' },
            { t: 'Afternoon', d: 'Swamimalai trek and Velavan Temple.' },
            { t: 'Evening', d: 'Telescope House sunset and zip-line.' } ],
      2: [ { t: 'Day 1', d: 'Lake, temple and viewpoints.' },
            { t: 'Day 2', d: 'Jalagamparai Falls, paragliding and departure.' } ],
      3: [ { t: 'Day 1', d: 'Arrival and lake.' },
            { t: 'Day 2', d: 'Trekking and adventure sports.' },
            { t: 'Day 3', d: 'Nilavoor Lake and departure.' } ],
    },
    reviews: [
      { name: 'Arun V.', city: 'Bengaluru', text: 'Easy Bengaluru–Yelagiri weekend. Driver was friendly and the booking with prefilled details was quick.' },
      { name: 'Pavithra S.', city: 'Chennai', text: 'Short hill trip from Chennai, great for the kids. Fair price and a clean cab.' },
    ],
  },
  {
    slug: 'hogenakkal', name: 'Hogenakkal', state: 'Tamil Nadu',
    img: null,
    tagline: 'The Niagara of India — coracle rides through carbonatite gorges where the Cauvery thunders down.',
    tags: ['Waterfalls', 'Adventure', 'Family Trip', 'Weekend Getaway'],
    dist: { chennai: 290, madurai: 350, bangalore: 130, coimbatore: 290, trichy: 280, salem: 110, erode: 160, theni: 390, dindigul: 300 },
    bestSeason: 'July – February', duration: 'Day trip – 2 days',
    weather: 'Warm 24–35°C; falls are most powerful after the monsoon.',
    roads: 'Good roads via Dharmapuri; easy access to the river.',
    attractions: [
      { n: 'Hogenakkal Falls', d: 'Powerful Cauvery cascades through rocky gorges.' },
      { n: 'Coracle Rides', d: 'Round-boat rides to the base of the falls.' },
      { n: 'Carbonatite Rocks', d: 'Among the oldest rock formations on earth.' },
      { n: 'Oil Massage & Fish Spa', d: 'Riverside traditional massages.' },
      { n: 'Melagiri Hills', d: 'Forested backdrop with viewpoints.' },
      { n: 'Theerthamalai Temple', d: 'Ancient hill temple near Harur.' },
    ],
    plans: {
      1: [ { t: 'Morning', d: 'Coracle ride to the main falls.' },
            { t: 'Afternoon', d: 'Riverside lunch with fresh fish and a massage.' },
            { t: 'Evening', d: 'Melagiri viewpoint and departure.' } ],
      2: [ { t: 'Day 1', d: 'Falls, coracle ride and river bathing.' },
            { t: 'Day 2', d: 'Theerthamalai Temple, Dharmapuri and departure.' } ],
      3: [ { t: 'Day 1', d: 'Arrival and riverside evening.' },
            { t: 'Day 2', d: 'Falls and coracle adventure.' },
            { t: 'Day 3', d: 'Nearby hills and departure.' } ],
    },
    reviews: [
      { name: 'Dinesh K.', city: 'Bengaluru', text: 'Bengaluru to Hogenakkal day trip — only 3 hours. The coracle ride was a blast and the driver waited patiently.' },
      { name: 'Saranya M.', city: 'Salem', text: 'Close from Salem, great family outing. Transparent fare and a comfortable cab.' },
    ],
  },
  {
    slug: 'pondicherry', name: 'Pondicherry', state: 'Puducherry',
    img: null,
    tagline: 'The French Riviera of the East — pastel boulevards, seaside cafés, Auroville and a calm spiritual air.',
    tags: ['Beach', 'Honeymoon', 'Family Trip', 'Weekend Getaway'],
    dist: { chennai: 160, madurai: 330, bangalore: 310, coimbatore: 360, trichy: 200, salem: 250, erode: 300, theni: 350, dindigul: 280 },
    bestSeason: 'October – March', duration: '1 – 2 days',
    weather: 'Warm coastal 24–34°C; pleasant winter evenings by the sea.',
    roads: 'Excellent ECR coastal highway from Chennai; flat and scenic.',
    attractions: [
      { n: 'Promenade Beach', d: 'Seafront walk with colonial landmarks.' },
      { n: 'Auroville & Matrimandir', d: 'Experimental township and golden meditation dome.' },
      { n: 'French Quarter', d: 'Pastel villas, cafés and the White Town.' },
      { n: 'Sri Aurobindo Ashram', d: 'Peaceful spiritual centre in the heart of town.' },
      { n: 'Paradise & Auroville Beach', d: 'Golden sands reached by boat or road.' },
      { n: 'Basilica of the Sacred Heart', d: 'Striking Gothic-style church.' },
    ],
    plans: {
      1: [ { t: 'Morning', d: 'French Quarter walk and Aurobindo Ashram.' },
            { t: 'Afternoon', d: 'Auroville and Matrimandir viewpoint.' },
            { t: 'Evening', d: 'Promenade Beach sunset and café dinner.' } ],
      2: [ { t: 'Day 1', d: 'White Town, ashram and Promenade.' },
            { t: 'Day 2', d: 'Auroville, Paradise Beach and departure.' } ],
      3: [ { t: 'Day 1', d: 'Arrival and seaside evening.' },
            { t: 'Day 2', d: 'Auroville, beaches and French Quarter.' },
            { t: 'Day 3', d: 'Chunnambar boathouse and departure.' } ],
    },
    reviews: [
      { name: 'Vignesh R.', city: 'Chennai', text: 'Chennai to Pondicherry on the ECR — beautiful coastal drive, on-time pickup and a clean Sedan.' },
      { name: 'Aishwarya T.', city: 'Trichy', text: 'Weekend in Pondy with friends. Easy booking, fair fixed fare and a smooth ride.' },
    ],
  },
];

// Embedded fare rules (mirror of js/app.js TARIFF) + Tempo Traveller.
const FARE_RULES = {
  local: {
    mini:      { base: 110, included: 3, perKm: 18 },
    sedan:     { base: 110, included: 3, perKm: 19 },
    suv:       { base: 120, included: 3, perKm: 22 },
    innova:    { base: 130, included: 3, perKm: 24 },
    traveller: { base: 250, included: 3, perKm: 28 },
  },
  outstation: {
    mini:      { perKm: 13, driverBata: 400 },
    sedan:     { perKm: 14, driverBata: 400 },
    suv:       { perKm: 18, driverBata: 400 },
    innova:    { perKm: 22, driverBata: 400 },
    traveller: { perKm: 26, driverBata: 600 },
  },
};

const VEHICLES = [
  { key: 'mini',      label: 'Mini',      seats: '4 seats' },
  { key: 'sedan',     label: 'Sedan',     seats: '4 seats' },
  { key: 'suv',       label: 'SUV / MUV', seats: '6 seats' },
  { key: 'innova',    label: 'Innova',    seats: '7 seats' },
  { key: 'traveller', label: 'Traveller', seats: '12 seats' },
];

module.exports = { DESTINATIONS, FARE_ORIGINS, INFO_ORIGINS, FARE_RULES, VEHICLES };
